import os
from dotenv import load_dotenv

load_dotenv()

# MongoDB
#MONGO_URI = os.environ.get("APPSETTING_MONGO_URI")
MONGO_URI = os.getenv("APPSETTING_MONGO_URI")

# OpenAI
#OPENAI_API_KEY = os.environ.get("APPSETTING_OPENAI_API_KEY")
#OPENAI_API_BASE = os.environ.get("APPSETTING_OPENAI_API_BASE")
#OPENAI_API_TYPE = os.environ.get("APPSETTING_OPENAI_API_TYPE")
#OPENAI_API_VERSION = os.environ.get("APPSETTING_OPENAI_API_VERSION")
#OPENAI_DEPLOYMENT_NAME = os.environ.get("APPSETTING_OPENAI_DEPLOYMENT_NAME")
OPENAI_API_KEY = os.getenv("APPSETTING_OPENAI_API_KEY")
OPENAI_API_BASE = os.getenv("APPSETTING_OPENAI_API_BASE")
OPENAI_API_TYPE = os.getenv("APPSETTING_OPENAI_API_TYPE")
OPENAI_API_VERSION = os.getenv("APPSETTING_OPENAI_API_VERSION")
OPENAI_DEPLOYMENT_NAME = os.getenv("APPSETTING_OPENAI_DEPLOYMENT_NAME")

# Alpaca
#ALPACA_API_KEY = os.environ.get("APPSETTING_ALPACA_API_KEY")
#ALPACA_SECRET_KEY = os.environ.get("APPSETTING_ALPACA_SECRET_KEY")
ALPACA_API_KEY = os.getenv("APPSETTING_ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.getenv("APPSETTING_ALPACA_SECRET_KEY")


# News API
#NEWS_API_KEY = os.environ.get("APPSETTING_NEWS_API_KEY")
#NEWS_API_SECRET = os.environ.get("APPSETTING_NEWS_API_SECRET")
#NEWS_API_ENDPOINT = os.environ.get("APPSETTING_NEWS_API_ENDPOINT")
NEWS_API_KEY = os.getenv("APPSETTING_NEWS_API_KEY")
NEWS_API_SECRET = os.getenv("APPSETTING_NEWS_API_SECRET")
NEWS_API_ENDPOINT = os.getenv("APPSETTING_NEWS_API_ENDPOINT")
